GraalVM support
kora-projects/kora pull request #1
Opened 2024-02-29 22:23 UTC by GoodforGod

Features:
- GraalVM support added and tested for:
  - Validation
  - Resilient
  - JDBC
  - R2DBC
  - Vertx
  - Cassandra
  - Cache:
    - Caffeine
    - Redis
  - HTTP Server Undertow
  - HTTP Client:
    - OkHttp
    - Async
    - JDK
  - JSON
  - Logging
  - OpenAPI management
  - HOCON config
  - YAML config
  - Metrics
  - Kafka

2024-04-15 09:46 UTC, Squiry requested changes

2024-04-15 09:46 UTC, Squiry commented on build.gradle
>          mavenLocal()
Раз уж влез в град файлы - mavenLocal у нас тут скорее вредный, чем полезный.

2024-04-15 09:46 UTC, Squiry commented on cache/cache-annotation-processor/src/main/java/ru/tinkoff/kora/cache/annotation/processor/aop/CacheInvalidateAopKoraAspect.java
> +            builder.add(".doOnSuccess(_result -> $L.invalidate($L));", operation.executions().get(0).field(), operation.executions().get(0).cacheKey().code());
Выглядит как будто бы код для другого пра!

2024-04-17 07:32 UTC, GoodforGod commented on application-graph/src/main/java/ru/tinkoff/kora/application/graph/internal/GraphImpl.java
> +        try {
а тут он и не нужен, это реактор инициализируется он не зависит loom это или нет

2024-04-22 10:01 UTC, Squiry commented on application-graph/src/main/java/ru/tinkoff/kora/application/graph/internal/GraphImpl.java
> +            var classReactorContext = Class.forName("ru.tinkoff.kora.common.util.ReactorContextHook");
Так, а что инициализация хука для контекста реактора делает вообще в графе?..

2024-04-22 11:30 UTC, Squiry commented on application-graph/src/main/java/ru/tinkoff/kora/application/graph/internal/GraphImpl.java
> +            var classReactorContext = Class.forName("ru.tinkoff.kora.common.util.ReactorContextHook");
Раньше он вызывался в статике в `Context`, потому что это про него. Почему теперь он вызывается в `GraphImpl`, который вообще в другой жарке лежит.

2024-05-07 12:43 UTC, Squiry approved these changes

2024-05-07 15:19 UTC, merged