Camunda7 Engine
kora-projects/kora pull request #28
Opened 2024-04-15 08:48 UTC by GoodforGod

- Camunda7 Engine module added

2024-04-22 10:07 UTC, Squiry requested changes

2024-04-22 10:07 UTC, Squiry commented on bpmn/bpmn-camunda7-rest-undertow/src/main/java/ru/tinkoff/kora/bpmn/camunda7/rest/CamundaAllowAllCorsFilter.java
> +//TODO точно ли нужен?
Нет, не нужен.

2024-04-22 10:15 UTC, GoodforGod commented on settings.gradle
> +    'bpmn:bpmn-camunda7-engine',
просто zeebe = camunda8, это прям отдельный движок и он разительно отличается от camunda обычной (camunda7)

2024-04-22 10:16 UTC, GoodforGod commented on bpmn/bpmn-camunda7-rest-undertow/src/main/java/ru/tinkoff/kora/bpmn/camunda7/rest/undertow/CamundaRestUndertowModule.java
> +            return new FakeCamundaRestHttpServer(httpServerConfig.get().publicApiHttpPort());
дак он все ровно скрыт как класс и его ни кто вне пакета не увидел бы

2024-04-22 11:34 UTC, Squiry commented on settings.gradle
> +    'bpmn:bpmn-camunda7-engine',
Ну давай тогда `camunda:camunda7-engine` и `camunda:camunda7-rest-undertow`. bpmn мне не нравится в руте.

2024-04-22 16:21 UTC, Squiry commented on bpmn/bpmn-camunda7-rest-undertow/src/main/java/ru/tinkoff/kora/bpmn/camunda7/rest/undertow/CamundaRestUndertowModule.java
> +            return new FakeCamundaRestHttpServer(httpServerConfig.get().publicApiHttpPort());
Он просто не нужен, какая разница скрыт он или нет?

2024-05-07 12:47 UTC, Squiry approved these changes

2024-09-16 15:33 UTC, merged